all:
  children:
    proxmox:
      hosts:
        pve-1:
          ansible_host: 10.10.100.3
          ansible_user: root
          proxmox_role: prod
        pve-2:
          ansible_host: 10.10.100.2
          ansible_user: root
          proxmox_role: dev
        pve-3:
          ansible_host: 10.10.100.5
          ansible_user: root
          proxmox_role: infra

    coreos_vms:
      children:
        db_vms:
          hosts:
            colossus-prod-db1:
              ansible_host: 10.10.100.110
              proxmox_node: pve-1
              vmid: 110
            colossus-dev-db1:
              ansible_host: 10.10.100.200
              proxmox_node: pve-2
              vmid: 210
        app_vms:
          hosts:
            colossus-prod-app1:
              ansible_host: 10.10.100.120
              proxmox_node: pve-1
              vmid: 120
            colossus-dev-app1:
              ansible_host: 10.10.100.220
              proxmox_node: pve-2
              vmid: 220

    infrastructure:
      hosts:
        pihole:
          ansible_host: 10.10.100.53
          ctid: 311
        cloudflared:
          ansible_host: 10.10.100.54
          ctid: 312
        traefik:
          ansible_host: 10.10.100.55
          ctid: 313
        semaphore:
          ansible_host: 10.10.100.57
          ctid: 315

    backup:
      hosts:
        pbs:
          ansible_host: 10.10.100.242
          ansible_user: root

    storage:
      hosts:
        truenas:
          ansible_host: 10.10.0.38
          ansible_user: admin
