---
# roles/pbs/handlers/main.yml

- name: Restart proxmox-backup-proxy
  ansible.builtin.systemd:
    name: proxmox-backup-proxy
    state: restarted

- name: Restart proxmox-backup
  ansible.builtin.systemd:
    name: proxmox-backup
    state: restarted
